- Entity/TicketManager.php
- Entity/TicketMessage.php
- Resources/translations/messages.de.xlf
- Resources/translations/messages.en.xlf
- Resources/translations/messages.es.xlf
- Resources/translations/messages.fr.xlf
- Resources/translations/messages.ru.xlf
- Resources/views/Macros/macros.html.twig
- Resources/views/Ticket/index.html.twig
- Resources/views/Ticket/new.html.twig
- Resources/views/Ticket/prototype.html.twig
- Resources/views/Ticket/show.html.twig
- improve ticket templates
- use macros for buttons and alerts
- use locale date formats
- add author column on index
> Improve templates

- Command/AutoClosingCommand.php
- README.md
- Resources/views/Ticket/show.html.twig
Hi,
Sorry it took time, I've been quite busy but i managed to work on it today.
So, I made a command with an argument (to choose the username of the updater) and an option to filter the resolved tickets by age.
I don't quite understand why in your command you look for a user 'system'
```
->setUser($userManager->findUserByUsername('system'))
```
https://github.com/hackzilla/TicketBundle/blob/master/Command/TicketManagerCommand.php#L59
> Add autoclosing command

- Resources/views/Ticket/index.html.twig
Use the TWBS3 template of the KNP Pagination on index
> update pagination template

- Controller/TicketController.php
- Entity/TicketMessageRepository.php
- Entity/TicketRepository.php
- Resources/views/Ticket/index.html.twig
Add filters for priority on index
> Priority filters

- DependencyInjection/Configuration.php
Fixed an error added with the last pull request
> fix a typo

- EventListener/FileSubscriber.php
- EventListener/UserLoad.php
- Manager/UserManager.php
- Resources/config/services.yml
- Resources/config/vich_uploader/TicketMessageWithAttachment.xml
- Resources/views/Ticket/show.html.twig
- Tests/Form/Type/TicketMessageTypeTest.php
- Tests/Form/Type/TicketTypeTest.php
- Tests/Manager/UserManagerTest.php
- TwigExtension/TicketGlobalExtension.php
There was an error in Hackzilla\Bundle\TicketBundle\Entity\TicketMessageWithAttachment.xml, wrong field name value (file).
Fixed value - "attachmentFile"
> Fix vich_config - property name, UserManager::hasRole(), hardcoded template path to prototype, UserLoad

- Resources/translations/messages.pt_BR.xlf
- add file of translation portuguese brazil.
> Add translation portuguese brazil

- .travis.yml
- Makefile
- composer.json
> Allow new major versions for existing dependencies

- .gitignore
- .travis.yml
- DependencyInjection/HackzillaTicketExtension.php
- Makefile
- Tests/Functional/Entity/User.php
- Tests/Functional/FunctionalTest.php
- Tests/Functional/TestBundle.php
- Tests/Functional/TestKernel.php
- Tests/Functional/WebTestCase.php
- composer.json
> Add missing dependencies and check for presence of `VichUploaderBundle` before trying to use it

- .styleci.yml
> Cherry picked `b455a21` from `develop` branch

- .php_cs
- .travis.yml
- Command/AutoClosingCommand.php
- Controller/TicketController.php
- DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
- DependencyInjection/HackzillaTicketExtension.php
- Entity/Traits/TicketMessageTrait.php
- Entity/Traits/TicketTrait.php
- Form/DataTransformer/StatusTransformer.php
- Form/Type/TicketMessageType.php
- Makefile
- Manager/TicketManager.php
- Manager/UserManager.php
- Model/TicketMessageInterface.php
- Resources/config/services.yml
- Tests/Form/Type/TicketMessageTypeTest.php
- Tests/Form/Type/TicketTypeTest.php
- Tests/Functional/FunctionalTest.php
- Tests/Functional/TestKernel.php
- Tests/Manager/UserManagerTest.php
- Tests/bootstrap.php
- composer.json
- phpunit.xml.dist
> [Tests] Some improvements for test suite

- UPGRADE-3.0.md
- composer.json
> Add `UPGRADE-3.0.md` in order to track major changes between 2.x and 3.0

- composer.json
See https://github.com/symfony/framework-bundle/commit/2b70f9290fcd1f87388526668ee86674b5802bfe.
> Update dependency constraint for "symfony/framework-bundle"

- Command/AutoClosingCommand.php
- Command/TicketManagerCommand.php
- Resources/config/services.yml
> Use `Command` as base for console command classes

- composer.json
> Exclude test files from "autoload" section

- composer.json
See https://github.com/KnpLabs/KnpPaginatorBundle/releases/tag/v4.0.0.
> Add support for "knplabs/knp-paginator-bundle:^4.0"

- composer.json
Allow "doctrine/doctrine-bundle:^2.0".
> Allow "doctrine/doctrine-bundle:^2.0"

- composer.json
The changes between version 4 and 5 seem fully compatible with the features that we implement:
* https://github.com/KnpLabs/KnpPaginatorBundle/releases/tag/v5.0.0
* https://github.com/KnpLabs/KnpPaginatorBundle/compare/v4.1.0...v5.0.0
> Allow to install "knplabs/knp-paginator-bundle:^5.0"

- Resources/views/Ticket/index.html.twig
- Resources/views/Ticket/new.html.twig
- Resources/views/Ticket/show.html.twig
- Resources/views/Ticket/show_attachment.html.twig
> Fix references to "hackzilla_ticket.templates.*" parameters

- Manager/TicketManager.php
- Tests/Manager/TicketManagerTest.php
|Bug fix?     |yes|
Issue introduced at be8f77a2.
> Fix bad call at `TicketManager::getTicketList()`

- Makefile
- Resources/translations/HackzillaTicketBundle.de.xlf
- Resources/translations/HackzillaTicketBundle.en.xlf
- Resources/translations/HackzillaTicketBundle.es.xlf
- Resources/translations/HackzillaTicketBundle.fr.xlf
- Resources/translations/HackzillaTicketBundle.it.xlf
- Resources/translations/HackzillaTicketBundle.nl.xlf
- Resources/translations/HackzillaTicketBundle.pt_BR.xlf
- Resources/translations/HackzillaTicketBundle.ru.xlf
- Resources/translations/messages.de.xlf
- Resources/translations/messages.en.xlf
- Resources/translations/messages.es.xlf
- Resources/translations/messages.fr.xlf
- Resources/translations/messages.it.xlf
- Resources/translations/messages.nl.xlf
- Resources/translations/messages.pt_BR.xlf
- Resources/translations/messages.ru.xlf
> Lint "*.xlf" files

- README.md
> Update "Version Matrix" section at `README.md`

- composer.json
|Bug fix?     |yes|
|Doc PR       |   |
> Explicitly require "doctrine/common"

- .github/dependabot.yml
|Fixed tickets|   |
|Doc PR       |   |
> Add configuration for Dependabot

- DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
- DependencyInjection/HackzillaTicketExtension.php
- Manager/TicketManager.php
- Manager/TicketManagerInterface.php
- Manager/UserManager.php
- Resources/config/services.yml
- Tests/Manager/TicketManagerTest.php
- composer.json
- phpstan.neon.dist
> Add support for "doctrine/persistence:^2.1"

- README.md
> Update URLs in status badges

- Resources/config/services.yml
> Fix argument 1 passed to `UserLoad::__construct()`

- Manager/TicketManager.php
Hi,
Priority and ticket creator did not save and I eventually had a doctrine error (installed in symfony 5).
With this fix, it works. I hope that it will work in any setup.
Regards.
> Bugfixes on ticket saving

- DependencyInjection/Configuration.php
- DependencyInjection/HackzillaTicketExtension.php
- Manager/TicketManager.php
- Manager/UserManager.php
- Model/PermissionsServiceInterface.php
- Model/PermissionsServiceTrait.php
- README.md
- Resources/config/manager.php
- Resources/doc/setup/install.md
- Tests/Manager/TicketManagerTest.php
Hi,
I made a PR some time ago to add custom permissions to access ticket and to display ticket list.
You asked me to rewrite it using reflexion class.
Here it is. I hope this is what you expected.
Regards.
> Custom permission service

- Controller/TicketAttachmentController.php
- Controller/TicketController.php
See https://github.com/hackzilla-project/TicketBundle/issues/263.
> fix(security): UserManager hasPermission() returned value is ignored
