EventListener/UserLoad.php

The listener causes issues any entity is loaded from a different entity manager other than default.
The listener should ignore any entity which is not part of this bundle.

UserLoad listener to ignore non bundle entites

---

DependencyInjection/Configuration.php
Resources/doc/setup/fosuserbundle.md
Resources/doc/setup/other.md

Also fix https://github.com/hackzilla/TicketBundle/issues/90 in config

Fix path to bin/console in documents

---

.travis.yml
composer.json

Flex applications mark "symfony/symfony" as conflicting dependency. See https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex.

Make "symfony/*" dependencies explicit

---

Manager/UserManager.php

[UserManager] Some minor improvements

---

Command/AutoClosingCommand.php
Controller/TicketAttachmentController.php
Controller/TicketController.php
Manager/TicketManager.php
Resources/views/Macros/macros.html.twig
Resources/views/Ticket/index.html.twig
Resources/views/Ticket/new.html.twig
Resources/views/Ticket/show.html.twig

Use "HackzillaTicketBundle" as translation domain instead of "messages"

---

.travis.yml
composer.json

* Provide "translation" service via "symfony/translation" instead of "sensio/framework-extra-bundle";
* Declare "SYMFONY_PHPUNIT_VERSION" at CI tests in order to avoid issues with nonexistent PHPUnit branches (see symfony/symfony#29265, sebastianbergmann/phpunit#3413).

[dependencies] Provide "translation" service via "symfony/translation" instead of "sensio/framework-extra-bundle"

---

Controller/TicketController.php
Manager/TicketManager.php
Manager/TicketManagerInterface.php
UPGRADE-3.0.md

|BC breaks?   |yes   |
* Renamed method `TicketManagerInterface::getTicketList()` to `TicketManagerInterface::getTicketListQuery()`
to clarify what it returns;
* `TicketManagerInterface::updateTicket()` now returns `void`, since the object (`TicketInterface`) it was returning before is the same as the provided in its argument 1.

Some minor changes at `TicketManager`

---

Command/AutoClosingCommand.php
Command/TicketManagerCommand.php
DependencyInjection/Configuration.php
Resources/config/services.yml

Remove some deprecations

---

Resources/config/services.yml
Tests/Functional/Command/ApplicationTest.php

Fix service injection at argument 3 for `AutoClosingCommand::__construct()`

---

phpunit.xml.dist

Fixes this warning:
```
PHPUnit 7.4.5 by Sebastian Bergmann and contributors.
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 13:
- Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.
```

Remove "syntaxCheck" config for PHPUnit

---

TwigExtension/TicketFeatureExtension.php
TwigExtension/TicketGlobalExtension.php
composer.json

Add explicit dependency against "twig/twig"

---

composer.json

* "symfony/twig-bundle" is required to call `render()` from controllers;
* "twig/twig" was moved to `conflict` section with the constraint `<1.34` in order to ensure its namespaced classes are available.

Replace "twig/twig" requirement with "symfony/twig-bundle"

---

Tests/Functional/FunctionalTest.php
Tests/Functional/Resources/views/base.html.twig
Tests/Functional/TestKernel.php
composer.json

Requirement for "knplabs/knp-paginator-bundle" was updated [from `^2.3` to `^2.6`](https://github.com/KnpLabs/KnpPaginatorBundle/compare/v2.3.2...v2.6.0#diff-0a26006f70eb61548221c2dd5b0c15f2L40), since versions previous to `v2.6.0` were using the service "templating.helper.router", which is not registered within the current dependencies.

Add tests for templates load

---

Form/Type/PriorityType.php
Form/Type/StatusType.php
Tests/EventListener/UserLoadTest.php
Tests/Form/Type/TicketMessageTypeTest.php
Tests/Form/Type/TicketTypeTest.php
Tests/Functional/TestKernel.php
Tests/Manager/UserManagerTest.php
phpunit.xml.dist

Update some calls to deprecated test methods

---

composer.json

Update constraint for "phpunit/phpunit" in order to avoid conflicts when the package is installed as a 3rd party dependency.

Update constraint for "phpunit/phpunit"

---

composer.json

Explicitly require "twig/twig" since it is used by the Twig ticket extensions

---

Command/AutoClosingCommand.php
Controller/TicketAttachmentController.php
Controller/TicketController.php
DependencyInjection/Configuration.php
DependencyInjection/HackzillaTicketExtension.php
Manager/TicketManager.php
Resources/translations/HackzillaTicketBundle.de.xlf
Resources/translations/HackzillaTicketBundle.en.xlf
Resources/translations/HackzillaTicketBundle.es.xlf
Resources/translations/HackzillaTicketBundle.fr.xlf
Resources/translations/HackzillaTicketBundle.it.xlf
Resources/translations/HackzillaTicketBundle.pt_BR.xlf
Resources/translations/HackzillaTicketBundle.ru.xlf
Resources/views/Macros/macros.html.twig
Resources/views/Ticket/index.html.twig
Resources/views/Ticket/new.html.twig
Resources/views/Ticket/show.html.twig
Tests/Functional/TestKernel.php
UPGRADE-3.x.md

|Deprecations?|yes|
This is a backport from PR #123.

Deprecate "messages" translation domain in favor of "HackzillaTicketBundle" (backport PR #123)

---

.gitattributes
.github/workflows/lint.yaml
.github/workflows/qa.yaml
.travis.yml
Component/TicketFeatures.php
Controller/TicketController.php
Entity/Traits/TicketMessageTrait.php
Entity/Traits/TicketTrait.php
EventListener/FileSubscriber.php
Form/Type/TicketMessageType.php
Form/Type/TicketType.php
HackzillaTicketBundle.php
Makefile
Manager/TicketManager.php
Manager/TicketManagerInterface.php
Manager/UserManager.php
Manager/UserManagerInterface.php
Model/TicketInterface.php
Model/TicketMessageInterface.php
Resources/config/doctrine/model/attachment/TicketMessageWithAttachment.orm.xml
Resources/config/doctrine/model/attachment/TicketWithAttachment.orm.xml
Resources/config/doctrine/model/plain/Ticket.orm.xml
Resources/config/doctrine/model/plain/TicketMessage.orm.xml
Resources/config/services.yml
Resources/config/vich_uploader/TicketMessageWithAttachment.xml
Tests/Manager/TicketManagerTest.php
TwigExtension/TicketFeatureExtension.php
composer.json
phpstan.neon.dist

Configure SCA through GH actions

---

.php_cs.dist
Form/DataTransformer/StatusTransformer.php
Model/TicketMessageInterface.php
Tests/Component/TicketFeaturesTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/HackzillaTicketExtensionTest.php
Tests/Entity/TicketMessageTest.php
Tests/Entity/TicketMessageWithAttachmentTest.php
Tests/Entity/TicketTest.php
Tests/EventListener/UserLoadTest.php
Tests/Form/DataTransformer/StatusTransformerTest.php
Tests/Form/Type/PriorityTypeTest.php
Tests/Form/Type/StatusTypeTest.php
Tests/Form/Type/TicketMessageTypeTest.php
Tests/Form/Type/TicketTypeTest.php
Tests/Functional/Entity/User.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestBundle.php
Tests/Functional/TestKernel.php
Tests/Functional/WebTestCase.php
Tests/Manager/UserManagerTest.php
Tests/TwigExtension/TicketFeaturesTest.php

Fix some PHP CS rules

---

README.md
Resources/translations/HackzillaTicketBundle.nl.xlf
Resources/translations/messages.nl.xlf

This PR address the comments left at #150, authored by @bghosts.
Closes #150.

[#150] add Dutch translation

---

Command/AutoClosingCommand.php
Command/TicketManagerCommand.php
Component/TicketFeatures.php
Controller/TicketAttachmentController.php
Controller/TicketController.php
DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
DependencyInjection/Configuration.php
DependencyInjection/HackzillaTicketExtension.php
Event/TicketEvent.php
EventListener/FileSubscriber.php
EventListener/UserLoad.php
Form/DataTransformer/StatusTransformer.php
Form/Type/PriorityType.php
Form/Type/StatusType.php
Form/Type/TicketMessageType.php
Form/Type/TicketType.php
Manager/TicketManager.php
Manager/UserManager.php
Tests/Component/TicketFeaturesTest.php
TicketRole.php
TwigExtension/TicketFeatureExtension.php
TwigExtension/TicketGlobalExtension.php

Narrow API marking classes as final

---

README.md

Add status badges for GitHub actions

---

Tests/Functional/FunctionalTest.php

|Fixed tickets|n/a |
|Doc PR       |n/a |

Mark `FunctionalTest::testConfiguredFileUploadSubscriber()` as skipped if "vich/uploader-bundle" is not available

---

DependencyInjection/Configuration.php

Use `::class` pseudo constants in `Configuration::getConfigTreeBuilder()`

---

Component/TicketFeatures.php
Form/Type/TicketMessageType.php
Tests/Component/TicketFeaturesTest.php
UPGRADE-3.x.md

Deprecate return other type than boolean from `TicketFeatures::hasFeature()`

---

Tests/Functional/TestKernel.php
phpstan.neon.dist

Remove `serialize()` and `unserialize()` methods from `TestKernel`

---

Resources/config/routing.yml
Resources/config/routing/ticket.yml

Modernize routing definition

---

Command/AutoClosingCommand.php
Command/TicketManagerCommand.php
Command/UserManagerAwareTrait.php
EventListener/UserLoad.php
Manager/UserManager.php
Manager/UserManagerInterface.php
Resources/config/services.yml
Tests/EventListener/UserLoadTest.php
Tests/Manager/TicketManagerTest.php
Tests/Manager/UserManagerTest.php

Add `UserManager::findUserByUsername()`

---

Resources/config/routing.xml
Resources/config/routing/hackzilla_ticket.xml
Resources/config/routing/ticket.yml
Resources/doc/setup/install.md
Tests/Functional/RoutingTest.php
Tests/Functional/TestKernel.php
Tests/Functional/routes.yaml
composer.json

Added XML routing

---

Controller/TicketController.php
Resources/views/Ticket/index.html.twig

Hi,
I found 2 minor bugs in ticket list pagination:
- user sort is not working, in fact the only field that will 100% be present seems to be email
- had to cas page number to int or it crashed when using php8
Regards.

fix pagination: order by user + next page crashed with php8
